DROP TABLE TEMPERATURE_VALUE IF EXISTS;
DROP TABLE TEMPERATURE_DETAILS IF EXISTS;
DROP TABLE WEATHER IF EXISTS;
DROP TABLE LOCATION IF EXISTS;

CREATE TABLE LOCATION(LOCATION_ID INTEGER NOT NULL AUTO_INCREMENT,LATITUDE FLOAT,LONGITUDE FLOAT,CITY VARCHAR(100),STATE VARCHAR(100),PRIMARY KEY(LOCATION_ID),UNIQUE KEY ID_UNIQUE(LATITUDE,LONGITUDE));


CREATE TABLE TEMPERATURE_VALUE(TEMPERATURE_ID INTEGER NOT NULL AUTO_INCREMENT,TEMPERATURE INTEGER NOT NULL, PRIMARY KEY(TEMPERATURE_ID));
CREATE TABLE WEATHER(ID INTEGER NOT NULL AUTO_INCREMENT,DATE DATE NOT NULL,LOCATION_ID INTEGER,PRIMARY KEY(ID));
CREATE TABLE TEMPERATURE_DETAILS(TEMPERATURE_DETAILS_ID INTEGER NOT NULL AUTO_INCREMENT,ID INTEGER,TEMPERATURE_ID INTEGER NOT NULL,PRIMARY KEY(TEMPERATURE_DETAILS_ID),FOREIGN KEY(ID) REFERENCES WEATHER(ID),FOREIGN KEY(TEMPERATURE_ID) REFERENCES TEMPERATURE_VALUE(TEMPERATURE_ID));
ALTER TABLE WEATHER
    ADD FOREIGN KEY (LOCATION_ID) 
    REFERENCES LOCATION(LOCATION_ID)